#! /bin/sh

set -e

case "$1" in
  configure|upgrade)
    #not a conffile
    if [ ! -e /etc/lightdm/lightdm.conf ]; then
        cp /usr/share/bodhi/lightdm/lightdm.conf /etc/lightdm/lightdm.conf
    elif [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --session=enlightenment || true
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --greeter=lightdm-gtk-greeter || true
    fi

    ;;
esac

if [ "$1" = "configure" ] ; then
  update-alternatives --install /etc/lightdm/lightdm-gtk-greeter.conf \
    lightdm-gtk-greeter-config-derivative \
    /etc/lightdm/bodhi-lightdm-gtk-greeter.conf 30
fi


#DEBHELPER#

